remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

#theme: minima
author: radl_hirsch
description: Dokumentation der Photovoltaik-Anlage Hirschlandstrasse 156

markdown: GFM

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - README.md
  - installation.md
  - issues.md
  - links.md
  - logs.md
  
